const SUITS=["bam","crak","dot"];
function buildDeck(){const d=[];SUITS.forEach(s=>{for(let n=1;n<=9;n++)for(let i=0;i<4;i++)d.push({t:"s",s,n});});["N","E","W","S"].forEach(v=>{for(let i=0;i<4;i++)d.push({t:"w",v});});["Red","Grn","Soap"].forEach(v=>{for(let i=0;i<4;i++)d.push({t:"d",v});});for(let i=0;i<8;i++)d.push({t:"f"});for(let i=0;i<8;i++)d.push({t:"j"});return d;}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function countTile(rack,fn){return rack.filter(fn).length;}
function dragons(rack,v){return v?countTile(rack,t=>t.t==="d"&&t.v===v):countTile(rack,t=>t.t==="d");}
function countNumSuit(rack,n,s){return countTile(rack,t=>t.t==="s"&&t.n===n&&t.s===s);}
function matchingDragon(rack,suit){if(suit==="bam") return dragons(rack,"Grn")+dragons(rack,"Soap");if(suit==="crak")return dragons(rack,"Red")+dragons(rack,"Soap");return dragons(rack,"Soap");}
function oppDragon(rack,suit){if(suit==="bam") return dragons(rack,"Red");if(suit==="crak")return dragons(rack,"Grn");return dragons(rack,"Red")+dragons(rack,"Grn");}
function spConsecutivePairBonus(h){const c={};h.forEach(t=>{const k=t.t==="s"?`s-${t.s}-${t.n}`:t.t==="w"?`w-${t.v}`:t.t==="d"?`d-${t.v}`:t.t==="f"?"f":"j";c[k]=(c[k]||0)+1;});let consecPairBonus=0;for(const suit of SUITS){const pairedNums=[];for(let n=1;n<=9;n++) if((c[`s-${suit}-${n}`]||0)===2)pairedNums.push(n);let maxRun=0,run=0,prev=null;for(const n of pairedNums){if(prev!==null&&n===prev+1)run++; else run=1;if(run>maxRun)maxRun=run;prev=n;}const runBonus=maxRun>=7?0.22:maxRun>=6?0.16:maxRun>=5?0.11:maxRun>=4?0.07:maxRun>=3?0.03:0;if(runBonus>consecPairBonus)consecPairBonus=runBonus;}return consecPairBonus;}
function simulate(iterations=10000){const deck=buildDeck();const stats={hands:iterations,dotMatchUsesRedOrGreen:0,bamOppUsesSoap:0,crakOppUsesSoap:0,anyConsecPairBonus:0,avgSoapInHand:0,avgDragonInHand:0,twoSuit_2026_anchor_hits:0};for(let i=0;i<iterations;i++){const h=shuffle(deck).slice(0,13);const red=dragons(h,"Red"),grn=dragons(h,"Grn"),soap=dragons(h,"Soap"),dotMatch=matchingDragon(h,"dot");if(dotMatch!==soap)stats.dotMatchUsesRedOrGreen++;if(oppDragon(h,"bam")!==red)stats.bamOppUsesSoap++;if(oppDragon(h,"crak")!==grn)stats.crakOppUsesSoap++;if(spConsecutivePairBonus(h)>0)stats.anyConsecPairBonus++;stats.avgSoapInHand+=soap;stats.avgDragonInHand+=red+grn+soap;const pairFits=[["bam","crak"],["bam","dot"],["crak","dot"]].some(([s1,s2])=>{const twos=countNumSuit(h,2,s1)+countNumSuit(h,2,s2);const sixes=countNumSuit(h,6,s1)+countNumSuit(h,6,s2);return twos>=3&&sixes>=2;});if(pairFits)stats.twoSuit_2026_anchor_hits++;}stats.avgSoapInHand=(stats.avgSoapInHand/iterations).toFixed(3);stats.avgDragonInHand=(stats.avgDragonInHand/iterations).toFixed(3);stats.anyConsecPairBonusPct=((stats.anyConsecPairBonus/iterations)*100).toFixed(2)+"%";stats.twoSuit_2026_anchor_hitsPct=((stats.twoSuit_2026_anchor_hits/iterations)*100).toFixed(2)+"%";return stats;}
const iterations=Number(process.argv[2]||10000);const stats=simulate(iterations);console.log(`Simulated ${iterations} random 13-tile racks`);console.table(stats);if(stats.dotMatchUsesRedOrGreen||stats.bamOppUsesSoap||stats.crakOppUsesSoap){process.exitCode=1;}
